### ISSUE TITLE
Soporte para authentication token

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/operadores#10]
Actualmente, el código de generación de la web hace una petición para obtener todas las issues, y luego una petición por issue para tener todos los datos necesarios.

Si el número de issues crece, y se espera que esto ocurra, la api de GitHub comenzará a devolver errores por superar la tasa de uso de la api sin autenticar. Por tanto, hace falta dar soporte a este código para usar un authentication token y tener acceso a un mayor límite de peticiones.

**Comment by Siotma** [comment]
Actualmente, esto se hace en [repostatistics](https://github.com/asrob-uc3m/repostatistics), ya que es necesario para recopilar información relativa a teams dentro de la organización. Sin embargo, no fui capaz de replicarlo en el código.

**Comment by David-Estevez** [comment]
Correcto. Yo me puedo encargar, no es difícil conseguirlo. Lo más crítico es asegurarse que el token no entra en ningún momento a formar parte del código hardcodeado, por seguridad (relacionado: https://github.com/asrob-uc3m/HackLab/issues/5).

**Comment by Siotma** [comment]
Te lo agradezco, totalmente de acuerdo. Yo si saco un rato también lo miraré.

**Comment by Siotma** [comment]
Esta issue se puede cerrar, @David-Estevez ?

**Comment by David-Estevez** [comment]
Sí, está solucionado a través de #19
