### ISSUE TITLE
Indicar el procedimiento de formación en la página de operadores

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/operadores#11]
En la [página de operadores](http://asrob.uc3m.es/printers/operators.html), se podría poner, aprovechando el primer container, la información necesaria para iniciar la formación.

**Comment by davidvelascogarcia** [comment]
@Siotma como idea, para ver qué os parece. Además de la formación bases de impresión tutelada, el manual de operador y de mantenimiento. Se podrían grabar un par de vídeos con los procesos y pasos de una impresión como ejemplo más visual para que la toma de contacto sea lo más suave posible.
Un par de vídeos de los componentes que la forman y otro con un ejemplo de impresión.

**Comment by David-Estevez** [comment]
Me mola lo de poner las instrucciones para ser operador (que te remita a GitHub y te diga qué hay que escribir en la issue, por ejemplo).

No he entendido muy bien lo que dice @davidvelascogarcia , pero estoy a favor de todo lo que sea grabar vídeos para documentar y formar.

**Comment by jgvictores** [comment]
>Me mola lo de poner las instrucciones para ser operador (que te remita a GitHub y te diga qué hay que escribir en la issue, por ejemplo).
No he entendido muy bien lo que dice @davidvelascogarcia , pero estoy a favor de todo lo que sea grabar vídeos para documentar y formar.

Idem!! :tada:

**Comment by Siotma** [comment]
> Me mola lo de poner las instrucciones para ser operador (que te remita a GitHub y te diga qué hay que escribir en la issue, por ejemplo).

En este sentido, se podría reutilizar la información `cómo convertirse en operador `del [Readme](https://github.com/asrob-uc3m/operadores/blob/master/README.md). Aunque también estaría bien aclarar primero qué información exactamente debería constar para que sea realmente útil.

Respecto a la documentación en vídeo soy totalmente partidario, aunque imagino que la experiencia en formar nuevos operadores nos irá diciendo qué tipo de cosas necesitan un mayor refuerzo.

**Comment by davidvelascogarcia** [comment]
Cómo ha quedado demostrado mis habilidades a la hora de explicarme no tienen límite ;).
Respecto a las grabaciones, la propuesta era que como complemento al manual de mantenimiento y de operador se podrían preparar un par de vídeos. Me refiero, la formación es presencial, sin embargo,  seria adecuado antes de ir a las sesiones haber revisado los manuales de mantenimiento e impresión puestos al día.  Quizá como complemento a esas lecturas un par de vídeos con las partes de las impresoras y un ejemplo de cómo imprimir pueda ayudar y ser más intuitivo y rápido al ser en formato vídeo. Al igual que si fuera un MOOC y se estuviera explicando en una clase presencial. Sobre todo con vistas a usuarios que nunca hubieran empleado una impresora 3D.
No sé si he llegado a explicarme mejor.

**Comment by Siotma** [comment]
> Me mola lo de poner las instrucciones para ser operador (que te remita a GitHub y te diga qué hay que escribir en la issue, por ejemplo).

Añadido un primer intento vía 4dc319fcd2c184f504b47f9b3939f3f964c54888

**Comment by David-Estevez** [comment]
> Añadido un primer intento vía 4dc319fcd2c184f504b47f9b3939f3f964c54888

Deployed!! http://asrob.uc3m.es/printers/operators.html

**Comment by Siotma** [comment]
Actualmente el procedimiento también está indicado en el [Readme](https://github.com/asrob-uc3m/operadores/blob/master/README.md) de este repo. Sin embargo, creo que no es tan visible como el de la web, por tanto yo lo quitaría del README y dejaría únicamente un enlace a la web.

**Comment by Siotma** [comment]
Readme actualizado via a1f28a3d0e4d5c3979a69100d0dc33d40eba4d40

**Comment by Siotma** [comment]
Para continuar hablando de la creación de soportes para la ayuda al proceso de formación he creado #22 , por tanto esta issue se puede cerrar.
