### ISSUE TITLE
Mejoras para la barra de navegación

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/operadores#13]
Actualmente la barra de navegación únicamente incluye dos ítems, y no estoy de acuerdo con ninguno de ellos:

- `ASROB`: redirige a la wiki. Tal vez sería más apropiado redirigir a la web.
- `Información básica`: redirige a la página de impresoras. Estoy de acuerdo con que haya un enlace entre ambas páginas, pero no debería llamarse así.

Por otra parte, sería interesante facilitar la navegación a través de la página añadiendo botones como:

- `Convertirse en operador`: salta automáticamente a la sección propuesta en #11 
- `Lista de operadores`: salta automáticamente a la lista

**Comment by Siotma** [comment]
Primer intento vía 0990624288b121619068a47809bcdb72f79ce0fd

**Comment by David-Estevez** [comment]
Deployed!! http://asrob.uc3m.es/printers/operators.html
