### ISSUE TITLE
Admisión en la lista de operadores

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/operadores#16]
Dado que aparecía en la [lista de operadores de la Wiki](http://asrob.uc3m.es/index.php/Operadores) como responsable y operador, solicito que se me incluya en la nueva. Mi tutor fue @Siotma.

**Comment by Siotma** [comment]
Confirmado, aparece en [esta versión de la lista de operadores (vigente hasta ayer)](http://asrob.uc3m.es/index.php?title=Operadores&oldid=12823) con el nombre de Jorge Ramírez, como responsable. También aparece en la [versión actual de la lista de operadores](http://asrob.uc3m.es/index.php?title=Operadores&oldid=12852) con el nombre de Jorge Ramírez como operador.
