### ISSUE TITLE
Petición operador!

### ISSUE THREAD

**Issue by wenflehecanario** [asrob-uc3m/operadores#17]
Solicitud de operador.
  - Estudio ingeniería eléctrica en la Universidad Carlos III de Madrid.
  -Uso de las impresoras 3D porque se diseñar piezas en 3D y nos viene bien al grupo para los coches velocistas.

**Comment by David-Estevez** [comment]
Doy fe de que @wenflehecanario  pertenece al grupo de RoboFactory, y de que sus niveles de motivación están siempre por las nubes. :blush:

**Comment by daavm** [comment]
Me ofrezco como formador. Cuando quieras quedamos en la nave y empezamos con la formación :D

**Comment by David-Estevez** [comment]
@wenflehecanario si hay más gente de vuestro grupo de RoboFactory que quieran aprender aprovechad para que os enseñen a todos juntos!

**Comment by wenflehecanario** [comment]
En la próxima quedada de ASROB sería genial 😁

**Comment by daavm** [comment]
Me parece bien. En cuanto sepamos el día de la próxima reunión de Printer One vemos si puedes/podéis venir. Será el lunes o el martes, ya te aviso

**Comment by Siotma** [comment]
No sé si es buena idea hacer coincidir las reuniones de un grupo de trabajo con la formación de operadores, ya que durante la formación las impresoras no estarán disponibles para realizar tareas del grupo de trabajo. En el caso de Printer One esto es bastante relevante.

Por otra parte, en caso de que haya más gente interesada en realizar la formación, aunque se realice todo el mismo día, debería gestionarse para cada uno con una issue independiente.

**Comment by David-Estevez** [comment]
Creo que se refería a la reunión de RoboFactory...

**Comment by daavm** [comment]
> Creo que se refería a la reunión de RoboFactory...

Si es así nos vemos mañana @wenflehecanario, aunque como dice @Siotma quizá no es buena idea hacer coincidir la formación con un grupo de trabajo.

**Comment by daavm** [comment]
Buenas. Mañana voy a estar en la uni gran parte del día. De 4 a 8 tenemos reunión de Printer One. Fuera de ese horario, si quieres, empezamos con la formación

**Comment by wenflehecanario** [comment]
Hola! Yo también estaré todo el día en la uni y solo estoy ocupado de 12 a
14 horas, tú dime la hora a la que te viene bien y allí estaré 😁

**Comment by daavm** [comment]
Te parece bien de 14:30 a 16:00?

**Comment by wenflehecanario** [comment]
Genial! Allí estaré

**Comment by wenflehecanario** [comment]
Buenas tardes, adjunto fotos de las 3 piezas impresas por:
Dédalo
![whatsapp image 2018-05-04 at 14 52 01 1](https://user-images.githubusercontent.com/33062755/39629024-2012917a-4fab-11e8-8d55-4b8a89c3d149.jpeg)

Hija-Resurrection
![whatsapp image 2018-05-04 at 14 52 11](https://user-images.githubusercontent.com/33062755/39629061-3abbcc12-4fab-11e8-9987-45d63578534e.jpeg)
![whatsapp image 2018-05-04 at 14 52 01](https://user-images.githubusercontent.com/33062755/39629062-3ad4bd8a-4fab-11e8-902c-2c23503933d2.jpeg)

Sin más, espero haber cumplido con las condiciones para ser operador.

**Comment by dmarcosm** [comment]
@wenflehecanario ha demostrado que tiene los conocimientos actualmente recogidos en el  manual de usuario, así como experiencia como para convertirse en  operador.
