### ISSUE TITLE
Program the website

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/operadores#2]
Esto viene de https://github.com/asrob-uc3m/impresoras-asrob/issues/29#issuecomment-337899204

Idea: crear un repositorio asrob-uc3m/Operadores. Gestionar la formación de operadores mediante issues, utilizando etiquetas como "Solicitud formación", "Solicitud renovación", y más. Quien quiere abre una issue con la etiqueta correspondiente y los operadores disponibles la reciben y pueden asignarse para dar la formación. Dentro de la issue se puede hacer un seguimiento del proceso incluyendo fotos de piezas impresas y otras habilidades impartidas. Cuando la formación esté completada el formador cierra la issue. Por último, un código similar al de https://github.com/asrob-uc3m/repostatistics recopila la información de las issues y genera automáticamente la lista de operadores utilizando el usuario que creó la issue, usuarios asignados, usuario que la cerró, y fechas asociadas. Incluso se podría programar la distinción entre operadores y antiguos operadores si se pone fecha de caducidad al título de operador.

Yo puedo encargarme de hacer hasta donde sepa y si lo necesito pido ayuda @David-Estevez .

**Comment by David-Estevez** [comment]
Haz un boceto de cómo te gustaría que fuese la web y vamos viendo cómo se podría hacer. Si quieres hacerla tú yo te guío en el proceso y te voy echando un cable, sin problema.

**Comment by David-Estevez** [comment]
Si lo he entendido bien, el workflow sería el siguiente:

1. Alguien abre una issue para solicitar formación / renovación
2. Algún operador existente lo ve y se asigna a la issue, da instrucciones de cuándo tendrá lugar la formación
3. Se lleva a cabo la formación, documentando en la issue los progresos
4. El operador cierra la issue

¿Qué sería entonces lo que queremos mostrar en una web? ¿Una lista de operadores? ¿Instrucciones de cómo llevar a cabo este proceso?

**Comment by David-Estevez** [comment]
Y otra cosa, que no sé si pertenece a esta issue o tendría que ir en otra issue / discursión... ¿Cómo podemos incentivar el que los operadores formen a otros operadores? Actualmente el proceso es voluntario... y acaban haciéndolo siempre los mismos (o nadie, lo cual es peor).

**Comment by Siotma** [comment]
> Si lo he entendido bien, el workflow sería el siguiente:
> 1. Alguien abre una issue para solicitar formación / renovación
> 2. Algún operador existente lo ve y se asigna a la issue, da instrucciones de cuándo tendrá lugar la formación
> 3. Se lleva a cabo la formación, documentando en la issue los progresos
> 4. El operador cierra la issue

Exacto. De esta forma se puede extraer toda la información necesaria de las issues:
- Operadores autorizados: usuarios que han abierto una issue con la etiqueta de formación / renovación, y que dicha issue está cerrada.
- Fecha de formación / renovación: fecha en que se cerró la issue.
- Operador(es) responsable(s) de la formación: usuarios asignados a la issue, uno de los cuales además cerrará la issue.

> ¿Qué sería entonces lo que queremos mostrar en una web? ¿Una lista de operadores? ¿Instrucciones de cómo llevar a cabo este proceso?

La web debería mostrar principalmente la lista de operadores, generada de forma automática a través de la información de las issues. Lo suyo sería disponer de una página con dos listas, en dos pestañas estilo [reportstatistics](http://asrob.uc3m.es/contributors/). Una lista con "operadores" activos y otra con "antiguos operadores". El mecanismo de distinción entre uno y otro sería la fecha de cierre de la issue de formación / renovación más reciente. Asimismo, se podría hacer uso de la etiqueta "invalid" para marcar aquellos operadores que, aunque aún no hayan caducado, quedan inactivos por cualquier otro motivo...

La estructura de la lista debería ser similar a la [actual](http://asrob.uc3m.es/index.php/Operadores). Aprovechando la infraestructura de GitHub, se podría optimizar el acceso a la información:
- Foto: avatar de GitHub.
- Nombre: nombre de perfil de GitHub.
- Correo: innecesario, ya que el medio de contacto sería a través de GitHub.
- Sitio web: perfil de GitHub (enlazable desde el nombre y / o el avatar).
- Fecha de formación: fecha de cierre de la última issue creada con etiqueta solicitud de formación / renovación.
- Nº de operadores formados: número de issues asignadas cerradas con etiqueta solicitud de formación / renovación.

**Nota:** He renombrado las etiquetas para que estén todas en inglés.

El resultado debería ser de este estilo (los enlaces de la tercera y cuarta columna son más pijada que otra cosa, no son imprescindibles):

| Foto | Nombre | Fecha de formación | Nº de operadores formados | 
|---|---|---|---|
| [![Avatar](https://avatars2.githubusercontent.com/u/6171234?v=4)](https://github.com/Siotma)| [Manuel Peña Fernández](https://github.com/Siotma) | [20/11/2017](https://github.com/asrob-uc3m/operadores/issues?utf8=%E2%9C%93&q=author%3ASiotma%20label%3A%22renewal%20request%22%20label%3A%22training%20request%22%20) | [0](https://github.com/asrob-uc3m/operadores/issues?utf8=%E2%9C%93&q=asignee%3ASiotma%20label%3A%22renewal%20request%22%20label%3A%22training%20request%22%20) |

Para formar nuevos operadores deberían seguirse esencialmente las instrucciones detalladas en el [manual de usuario](https://github.com/asrob-uc3m/impresoras-user-manual-i3), el cual se debería ir actualizando conforme la experiencia de uso lo requiera, que para eso lo tenemos.

Respecto a un incentivo para formar nuevos operadores, merece la pena discutirlo en otro foro para no despistar este.

**Comment by Siotma** [comment]
Primera versión disponible vía c99beaf9893d35bbc211045fda511322dcbd8c8a

**Comment by Siotma** [comment]
Ahora mismo, faltaría:

- [ ] Habilitar la posibilidad de hacer login mediante un authentication token para [disponer de un mayor número de requests](https://developer.github.com/v3/#rate-limiting)

- [ ] También haría falta abrir nuevas issues para probar la estabilidad del programa

- [ ] Y por último, poner la web en línea y programar las ejecuciones del programa en el servidor

**Comment by David-Estevez** [comment]
Tomo el relevo y comienzo con las tareas de sysadmin para poner esto online.

**Comment by Siotma** [comment]
De acuerdo. Pues a falta de mejoras progresivas que haya que incluir, y a la vista de https://github.com/asrob-uc3m/operadores/pull/7 creo que esta issue está completa porque todo lo que falta tiene su propia issue.
