### ISSUE TITLE
Peticion operador

### ISSUE THREAD

**Issue by Ruben-MR** [asrob-uc3m/operadores#23]
Buenas. Soy del grupo de robofactory de asrob. Necesitaria  ser operador de impresoras para imprimir las piezas necesarias para los proyectos de la asociacion y demas.

**Comment by daavm** [comment]
Aprovechando que hay otro miembro de RoboFactory pendiente de recibir la formación, creo que lo lógico sería que recibieseis la formación a la vez, por aquello de ahorrar tiempo.

**Comment by Ruben-MR** [comment]
Perfecto, yo no tengo problema, tengo ahora bastante disponibilidad de horarios, asi que cuando prefieras.

**Comment by daavm** [comment]
Mañana he quedado a las 14:30 con  @wenflehecanario en la nave, estaremos hasta las 4 o así. Pásate si quieres

**Comment by Ruben-MR** [comment]
Perfecto, no se si podré estar exactamente a las 14:30 pero si que me acercaré, gracias.

**Comment by JorFru** [comment]
@Ruben-MR ya es operario certificado #29 validado por @jorfru
La validación de Rubén fue durante una reunión de RoboFactory, y no me enteré de que había otra persona interesada ni se manifestó ese día.

Cerramos esta issue y esperamos a que la otra persona interesada abra la suya?

**Comment by Siotma** [comment]
No tiene sentido que la misma persona tenga a la vez una issue de formación abierta y otra cerrada. Lo que sí hubiera sido buena idea es reutilizar la misma en vez de abrir otra distina.

Dado que hay mucha más documentación en #29 que en esta, esta creo que se puede dar por invalidada para no liar al sistema entre una y otra.

**Comment by JorFru** [comment]
No nos dimos cuenta de que ya estaba abierta, Sorry.
