### ISSUE TITLE
Petición operario! 

### ISSUE THREAD

**Issue by btacad** [asrob-uc3m/operadores#24]
Buenos días,

Mi nombre es Héctor José Muñoz Díaz, becario del departamento de mecánica y  miembro del equipo FUC3M. Realicé la formación con David velasco hace unos días. Llevo con impresoras 3d desde 2012 y actualmente estoy diseñandome una voladora tipo ultimaker.
Me gustaría darme de alta como operador para poder usar las impresoras en los proyectos.
Un saludo,

**Comment by davidvelascogarcia** [comment]
En efecto, se realizó la formación con las impresoras Blacky e Hija Resurrection. Adjunto capturas de algunas de las piezas impresas con el fin de documentar y verificar la issue.
![img_20171128_202227](https://user-images.githubusercontent.com/29423648/33990469-61fa5efa-e0cb-11e7-9bb3-16973208dbb8.jpg)

Figura 1. Gato de calibración

![img_20171128_165105](https://user-images.githubusercontent.com/29423648/33990512-86db9bd0-e0cb-11e7-85be-316c5f7e1d44.jpg)

Figura 2. Cubo de calibración

![img_20171128_190512](https://user-images.githubusercontent.com/29423648/33990579-c19a714c-e0cb-11e7-8c2d-9e21ce82542c.jpg)

Figura 3. Espiral de calibración

A su vez, se imprimieron otro par de gatos de calibración escalados para reducir el gasto de material.
