### ISSUE TITLE
Petición operador

### ISSUE THREAD

**Issue by jesus-gonzalez-gil** [asrob-uc3m/operadores#26]
Buenas tardes.

Mi nombre es Jesús, estaría interesado en realizar la formación de operador en impresión 3D si fuera posible.

Un saludo.

**Comment by davidvelascogarcia** [comment]
Buenas tardes.

Me ofrezco voluntario para la formación si aún no hay ningún operador asignado.

**Comment by davidvelascogarcia** [comment]
Tras revisar el horario de uso de las impresoras, para evitar coincidencias con otras formaciones o grupos de trabajo en ASROB, he observado que mañana por la tarde está disponible.
Aunque es un poco imprevisto, por casualidad, ¿mañana tendría disponibilidad por la tarde, para poder acudir a una sesión?.

Un saludo.

**Comment by jesus-gonzalez-gil** [comment]
Por mi parte no hay ningún problema, actualmente estoy disponible.

**Comment by davidvelascogarcia** [comment]
Perfecto, que le parecería sobre las 15:00, en la nave en el aula 1.0.B06.

**Comment by davidvelascogarcia** [comment]
Perfecto, mañana a las 15:00.

Un saludo.

**Comment by davidvelascogarcia** [comment]
Durante la sesión del día 30/01/2018, se ha realizado una reunión de formación conjunta como requerimiento de operador en impresion 3D.
Durante la misma se han realizado prácticas con las impresoras Blacky, Hija Resurrection y Dédalo.
Se han realizado pruebas de calentamiento, control manual, escalado y movimiento de la pieza con los respectivos mallados con slicer y viendo los efectos de la calidad de la impresión sobre la duración de la misma.
A su vez se llevó a cabo la unión del bobinado sobre el extrusor para la práctica.
Finalmente se realizó la impresión de diversas piezas, principalmente de calibración para comprobar el correcto funcionamiento y a su vez reducir el gasto de material al mínimo posible.
Adjunto capturas de algunas de las piezas impresas.

![img_20180130_155638](https://user-images.githubusercontent.com/29423648/35584616-d5e125ac-05f5-11e8-9e51-b27c937d01e6.jpg)

Figura 1.

![img_20180130_155642](https://user-images.githubusercontent.com/29423648/35584656-f3ec34c4-05f5-11e8-9031-454ba43b1996.jpg)

Figura 2.

Nota: Pido disculpas por la calidad de la captura de grueso de impresiones

![img_20180130_164035](https://user-images.githubusercontent.com/29423648/35584704-1919a498-05f6-11e8-9276-86474f6b3e8c.jpg)

Figura 3.

Finalizado y cierro la issue abierta.

**Comment by davidvelascogarcia** [comment]
Buenos días.

Adjunto los links comentados en la sesión de ayer.
URL, para la reserva de impresoras:
http://asrob.uc3m.es/printers/
URL, para la publicación de incidencias y dudas sobre las impresoras:
https://github.com/asrob-uc3m/impresoras-asrob/issues

Un saludo.
