### ISSUE TITLE
Quiero ser operador!

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/operadores#28]
Soy estudiante en la UC3M, asociaciado habitual en ASROB y desde el comienzo de la rama, en PrinterOne.
Me gustaría figurar en la lista de operadores, con el objetivo de formar a otros operadores.

Menciono a @Siotma para que se apunte el tanto porque él fue quien me enseñó la gran mayoría de lo que sé sobre impresoras. Muchas gracias tío!

Justifico a continuación tres piezas que he impreso yo solito.

![photo_2018-01-31_19-54-38](https://user-images.githubusercontent.com/11017088/35641495-a090625c-06c0-11e8-840a-abf74052a343.jpg)
Esta es una de las primeras piezas que imprimí en PrinterOne, que son piezas que todavía se siguen usando en Hija Resurrection.

![photo_2018-01-31_19-54-36](https://user-images.githubusercontent.com/11017088/35641537-bb402042-06c0-11e8-8a04-e02190fe6edd.jpg)
Esta pieza la pongo porque la foto quedó chula

![photo_2018-01-31_19-54-39](https://user-images.githubusercontent.com/11017088/35641558-cafa201e-06c0-11e8-89fe-de5784a7d56c.jpg)
Y bueno, esta va un poco de coña. Resulta que tengo un vicio insano por imprusar y he tenido que hacerme un letrero para recordarme que de vez en cuando sea una persona normal.

Gracias!

**Comment by Siotma** [comment]
@JorFru ha demostrado que tiene los conocimientos actualmente recogidos en el [manual de usuario](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/), así como gran experiencia, también en el ajuste de perfiles de impresión, siendo todo ello suficiente como para convertirse en operador.
