### ISSUE TITLE
Petición Operador

### ISSUE THREAD

**Issue by Ruben-MR** [asrob-uc3m/operadores#29]
Buenas!
Abro la issue para realizar la solicitud de operador, he estado imprimiendo las piezas de las fotos adjuntas bajo supervisión de otro operador. 

Para la impresión de dichas piezas, antes de llevar a cabo el proceso con cada una de ellas, se tuvo que ajustar la nivelación en el eje Z en ambos lados para obtener un mejor resultado, además de ajustar un mayor número de vueltas del skirt para poder apreciar mejor si el calibrado se había realizado bien.
En todo momento se procuró alcanzar las temperaturas adecuadas (y porque no funciona en caso contrario) y echar laca antes de imprimir cada pieza, si bien en el caso de una de las piezas cilíndricas no fue suficiente, dando como resultado que en medio de la impresión esta fuera desplazada y finalmente repetida.

En el caso de las piezas pequeñas tuvimos que realizar un escalado en las tres direcciones y una rotación en el eje X para evitar que un par de huecos quedaran mal. Esto, sin embargo, desencadenó en otro problema, el puente de la parte superior, para el cual tuvimos que crear una estructura de soporte y que el material no colgara, si bien el programa colo generó soportes en los bordes del puente y no en su totalidad (cosa que no pasó a la hora de imprimir las piezas cilíndricas).

Además se tuvo que reducir la velocidad de impresión para los puentes  debido a que el extrusor se movía a más velocidad de la que el plástico salía, lo cual causaba que en algunas partes no se creara la primera capa de soporte y parte del material cayera, como se puede ver en una de las piezas.

Básicamente, eso es lo que estuvimos haciendo, además de hacer un repaso de las funciones del programa. Abajo dejo las imágenes de las piezas finales.

![photo6032996288901000088](https://user-images.githubusercontent.com/32171451/35777082-db6fd044-09a7-11e8-959e-9ee52b7f2859.jpg)
![photo6032996288901000089](https://user-images.githubusercontent.com/32171451/35777084-e20af708-09a7-11e8-8553-136a024558e9.jpg)
![photo6032996288901000090](https://user-images.githubusercontent.com/32171451/35777085-e3f037b8-09a7-11e8-87e2-6239f7dff4fa.jpg)

**Comment by JorFru** [comment]
Hola! el día 31 estuve con Rubén enseñándole cómo funcionaban las máquinas y finalmente imprimió sus tres piezas satisfactorias.
Rubén pertenece al grupo RoboFactory y para su proyecto robótico necesitaba ciertas piezas para su desarrollo. A si que allí mismo aproveché para enseñarle y validarle, porque imprimirá más piezas para RoboFactory.

Elegimos a Hija para imprimir, porque su nuevo display nos llamaba mucho la atención. Por desgracia nos la encontramos con el carro torcido a causa de que la tuerca del husillo derecho estaba fuera de su hueco en la pieza que sujeta el eje X. Para recalibrar la horizontalidad de X, Rubén modificó la altura de los husillos y del final de carrera hasta comprobar que la primera capa si iba a imprimir bien. Utilizamos el método del ojímetro y de prueba y error.

Primero imprimió los soportes de motor, le enseñé a ajustar parámetros generales de los fileteadores disponibles, por ejemplo sobre cómo poner soportes. El primer resultado no nos gustó porque los puentes habían quedado fatal (velocidad de puentes demasiado rápida), pero en vez de cambiar esa velocidad, decidimos cambiar la orientación de la pieza para conseguir otra dirección del puente más conveniente.

Después de haber comprobado que los soportes de Slic3r no nos gustaban, imprimimos la rueda con Cura y el resultado nos gustó.


Certifico que @Ruben-MR se desanvuelve correctamente con nuestras impresoras y conoce su funcionamiento, reglas de seguridad y además algún truco para conseguir mejor calidad.
