### ISSUE TITLE
Solicitud de operador

### ISSUE THREAD

**Issue by Tamayoo3** [asrob-uc3m/operadores#32]
Soy estudiante de la carlos III de ingenieria electronica industrial y automatica y acabo de entrar en la asociacion ASROB de la UC3M.

**Comment by Tamayoo3** [comment]
He realizado mi primera pieza, y ha sido supervisada por @GioSunrider, es la siguiente:
![img-20180315-wa0006](https://user-images.githubusercontent.com/36888870/37484644-099f9100-2881-11e8-9b40-e1649de6d168.jpg)

**Comment by Tamayoo3** [comment]
Mi segunda pieza es el copo de nieve.
![img_20180315_202216](https://user-images.githubusercontent.com/36888870/37486628-f2e41da4-2886-11e8-89a6-7f05820cbf45.jpg)

**Comment by Tamayoo3** [comment]
Llavero de baby groot
![img_20180315_203301](https://user-images.githubusercontent.com/36888870/37487018-2c5d6ff8-2888-11e8-8c32-211d518ddab8.jpg)

**Comment by GioSunrider** [comment]
Proceso de entrenamiento completado. El Padawan ha desmostrado conocer las impresoras y conseguir que impriman correctamente. Tenemos un nuevo caballero Jedi, digo operador.
