### ISSUE TITLE
Solicitud operador

### ISSUE THREAD

**Issue by diegodevigo** [asrob-uc3m/operadores#35]
Hola, soy Diego estudiante de primer año en la uc3m. Buscaba hacerme operador porque mi anet a veces no funciona y aliexpress tarda mucho con los envios.

**Comment by GioSunrider** [comment]
@diegodevigo  ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario, así como experiencia como para convertirse en operador.
