### ISSUE TITLE
Formación como Operador

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/operadores#41]
Hola buenas, formo parte de Asrob y estoy en la rama de Printer One y quería formarme como operador para poder usar las impresoras.

**Comment by jorgercobo** [comment]
Primeras dos piezas

![photo_2018-11-07_20-52-34](https://user-images.githubusercontent.com/9537923/48157238-67a87100-e2cf-11e8-9db8-60d6748f95d7.jpg)
![photo_2018-11-07_20-53-03](https://user-images.githubusercontent.com/9537923/48157239-68410780-e2cf-11e8-8702-d2ffbb9e7fa8.jpg)

**Comment by MrTommyGuns** [comment]
3era impresión. Realizada con Spicy recién calibrada.

![photo6012744203840368389](https://user-images.githubusercontent.com/36898802/48587779-c2c40e80-e934-11e8-819c-d68c181cb795.jpg)

**Comment by jorgercobo** [comment]
@MrTommyGuns  ha demostrado que tiene los conocimientos actualmente recogidos en el [manual de usuario](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/) y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.
