### ISSUE TITLE
Solicitud formación operador

### ISSUE THREAD

**Issue by L4g0** [asrob-uc3m/operadores#43]
Hola,
Formo parte de Asrob, en el grupo Printer One y quería formarme como operador para poder usar las impresoras.

Muchas gracias :)

**Comment by L4g0** [comment]
Primera pieza, "mejora" para el ajuste de cama. Supervisado por @MrTommyGuns 
![image](https://user-images.githubusercontent.com/23212123/48800236-7f3d1c00-ed09-11e8-858a-d2c93c73ea7f.png)

**Comment by L4g0** [comment]
Segunda pieza, guía para filamento para Spicy. Supervisado por @MrTommyGuns 
![image](https://user-images.githubusercontent.com/23212123/51785564-023f8000-215a-11e9-8b8b-4c443afde528.png)

**Comment by L4g0** [comment]
Tercera pieza w/ @GioSunrider 

![image](https://user-images.githubusercontent.com/23212123/53590609-77a3d380-3b92-11e9-9d0e-38d9ebd31445.png)

**Comment by GioSunrider** [comment]
@L4g0 ha demostrado en las sucesivas reuniones de Printer One que tiene los conocimientos actualmente recogidos en el [manual de usuario](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/), así como experiencia siendo ambos más que suficientes como para convertirse en operador.
