### ISSUE TITLE
No aparezco en la lista de operadores

### ISSUE THREAD

**Issue by DiegoGarciaX2** [asrob-uc3m/operadores#44]
El curso anterior realice los tramites para ser operador pero no aparezco en la lista de operadores de la web.

**Comment by Siotma** [comment]
Sí que apareces en la lista de operadores: http://asrob.uc3m.es/printers/operators.html

![imagen](https://user-images.githubusercontent.com/6171234/47604540-8ec39080-d9fb-11e8-917c-ff2e5b3fb4b8.png)
