### ISSUE TITLE
Formacion Operador

### ISSUE THREAD

**Issue by MarioPrinter** [asrob-uc3m/operadores#46]

**Comment by MarioPrinter** [comment]
Buenaaas , formo parte de Asrob, en el grupo Printer One y quería formarme como operador para poder usar las impresoras. Un Saludo

**Comment by MarioPrinter** [comment]
Aquí adjunto imágenes de mis impresiones para la formación de operador

![photo5983581015123276303](https://user-images.githubusercontent.com/45212155/69836473-47848080-1249-11ea-8f49-5691b864c63c.jpg)
![photo5983581015123276304](https://user-images.githubusercontent.com/45212155/69836474-49e6da80-1249-11ea-9786-a7717e5b4df5.jpg)
![photo5983581015123276305](https://user-images.githubusercontent.com/45212155/69836475-4b180780-1249-11ea-9ec0-f25ef328e395.jpg)
![photo5983581015123276306](https://user-images.githubusercontent.com/45212155/69836476-4c493480-1249-11ea-80c1-1bc36a7ef40a.jpg)

**Comment by MrTommyGuns** [comment]
@MarioPrinter ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.

Enhorabuena ☺️
