### ISSUE TITLE
Repasar los enlaces de la web

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/operadores#48]
Es necesario repasar todos los Links que redirigen a la pagina de la lista de operadores. Actualmente alguno te lleva a https://asrob.uc3m.es/printers/operators.html actualmente sin servicio, ya que el link bueno es wiki.asrob.uc3m.es/printers/operators.html

**Comment by jgvictores** [comment]
Actualizaciones hechas en este repo:
- https://github.com/asrob-uc3m/operadores/commit/523d7edee52e86e5bb81e96474397e32f2e161fe
- https://github.com/asrob-uc3m/operadores/commit/47a3fe048c179681356f6c9529f5fb7ec829c50d
- https://github.com/asrob-uc3m/operadores/commit/27701c0dc452b32eb6aa64eccdf2f90e613616f5
- Actualización de la descripción de repo de GitHub

Y tb:
- https://github.com/asrob-uc3m/printers-status-webpage/commit/84c62fcd716253965b06f2e0d43c42d9ffe07411

**Comment by GioSunrider** [comment]
Genial, he repasado y no encuentro más errores. Puedes cerrar la issue 😊

**Comment by jgvictores** [comment]
Guay!
