### ISSUE TITLE
Actualizar los Criterios de Validacion

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/operadores#49]
Actualmente, la mayoria de las personas formadas se encuentran en activo, pero se muestran en necesitan validacion. Habria que dar una vuelta de tuerca a los criterios para evitar este problema.

Por ello propongo un sistema de 4 años (lo que "dura la vida universitaria") o un sistema por actualizaciones (por ejemplo cuando actualizemos a la gestion por Octoprint).

**Comment by David-Estevez** [comment]
No veo el problema de que esa gente necesite validación. Validación no significa tener que volver a hacer la formación, sino que necesitan que alguien que esté en activo dé fé de que esa formación sigue siendo válida y los conocimientos que tienen esos operaciones siguen vigentes. Sólo en caso de que los conocimientos no sirvan habría que volver a formarles.

El único problema que veo es que se os pase a todos el pedir la validación y no haya ningún operador validado para validar al resto... :joy:

**Comment by GioSunrider** [comment]
Me da miedo la segunda parte. La probabilidad que se nos pase es enorme.

**Comment by David-Estevez** [comment]
Ponéos un recordatorio en calendar o algo, ¿no? :joy:

**Comment by GioSunrider** [comment]
Acabo de revisar la página y no es que estemos en validación, estamos en Antiguos Operadores.

**Comment by jgvictores** [comment]
Sí, el criterio lleva igual desde el primer commit, que según entiendo se pasa a Antiguos tras 1 año de no formar a nadie (lo digo de forma totalmente objetiva, sólo por facilitar la labor en caso de decidir modificar el criterio): https://github.com/asrob-uc3m/operadores/blob/85685c65cc6ce961b2ff1615b3374417a0bb88a5/operadores.py#L127-L131

**Comment by GioSunrider** [comment]
Pues hay un bug, si ese es el criterio, en mi caso hace 11 y hace 8 meses que realice una formacion. Lo cual no concuerda con el año sin formar a nadie.

**Comment by jgvictores** [comment]
La resta como tal estaría bien, porque sitúa la formación en Nov 2017. Habría que ver por qué lo sitúa en Nov 2017 si realizaste una formación más recientemente.
![screenshot from 2019-02-09 16-43-42](https://user-images.githubusercontent.com/4448588/52522766-fc818880-2c89-11e9-88e7-d7698b4f271c.png)

**Comment by GioSunrider** [comment]
Porque mi formación fue en Noviembre 2017, pero la última formación que valide fue a Tamayo y a Diego que fue hace 10 y 11 meses.

**Comment by jgvictores** [comment]
Ah ok, entonces habré entendido el código mal. Estará puesto 1 año a partir de la formación.

**Comment by GioSunrider** [comment]
Continua en #58
