### ISSUE TITLE
Solicitud curso operador

### ISSUE THREAD

**Issue by fervh** [asrob-uc3m/operadores#51]
Hola buenass,
Soy Fernando de primero de Ingeniería Electrónica y Automática, y tengo un drone y siempre he querido hacer mis impresiones 3d pero no he tenido posibilidad :) 
Graciasss

**Comment by MrTommyGuns** [comment]
Buenas!

¿Estás en algún grupo de la asociación?¿Tienes Telegram?
Si es así, mandame un mensaje si quieres y podriamos concretar algunos días que nos vayan bien y la realizas.

Puedes hablarme por telegram a través del user "TommyGuns".

Un saludo!

**Comment by velafpv** [comment]
Hola, 
Ya te he hablado por telegram 
😄

**Comment by velafpv** [comment]
![a839d2c0-209c-473b-902a-a501e1f1d776](https://user-images.githubusercontent.com/55854056/66761453-57682100-eea4-11e9-815e-d07fe30a00aa.jpg)

Primera pieza impresa en 3D, con los consejos de @MrTommyGuns 😄

**Comment by velafpv** [comment]
![e8d4814e-5013-4c2c-8742-3737002e9e95](https://user-images.githubusercontent.com/55854056/66761653-b9288b00-eea4-11e9-93aa-382a72503a82.jpg)
![88447f30-149c-4cff-892f-f61c4e369464](https://user-images.githubusercontent.com/55854056/66761632-ad3cc900-eea4-11e9-87e3-4e9b49d78f86.jpg)
![14c28ef9-ec15-477a-a183-30ceca2dfbf6](https://user-images.githubusercontent.com/55854056/66761640-b037b980-eea4-11e9-8f97-a9b560c39e9f.jpg)
Tapita para la lipo que encaja al milímetro 💯

**Comment by fervh** [comment]
![neck](https://user-images.githubusercontent.com/55854056/67513995-44233580-f69c-11e9-8313-0755edec4f95.jpg)
Última pieza 😄

**Comment by MrTommyGuns** [comment]
@fervh ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.

Enhorabuena ☺️
