### ISSUE TITLE
Curso Operador

### ISSUE THREAD

**Issue by DaniDru** [asrob-uc3m/operadores#52]
Muy buenas! 
Estoy interesado en el uso de impresoras 3D y me encantaría aprender a utilizar los equipos disponibles en ASROB. Los proyectos cada vez son más específicos y requiere de piezas específicas. 
Un cordial saludo! Muchas gracias!

**Comment by MrTommyGuns** [comment]
Buenas!! Un día de estos quedamos y le damos caña al tema

**Comment by DaniDru** [comment]
Primera pieza para un teclado casio que le faltaba la tapa de las pilas

![photo_2019-10-08_12-30-32](https://user-images.githubusercontent.com/48059714/66389075-cd154e00-e9c7-11e9-848b-e622dc54b5c6.jpg)
![photo_2019-10-08_12-32-43](https://user-images.githubusercontent.com/48059714/66389076-cd154e00-e9c7-11e9-99ff-ebb31b0cdd32.jpg)
![photo_2019-10-08_12-32-48](https://user-images.githubusercontent.com/48059714/66389077-cd154e00-e9c7-11e9-9175-fe8551037bdc.jpg)

**Comment by DaniDru** [comment]
Cymbal sleeve. Pieza de sustitución para el soporte de un plato de batería (instrumento de percusión) que salió mal debido a la velocidad de impresión que deshizo el tubo central. 

![photo_2019-10-15_16-39-26](https://user-images.githubusercontent.com/48059714/66841744-729d6400-ef6a-11e9-8b09-641446fd4843.jpg)
![photo_2019-10-15_16-39-34](https://user-images.githubusercontent.com/48059714/66841745-729d6400-ef6a-11e9-9f34-784e6d58af04.jpg)
![photo_2019-10-15_16-39-38](https://user-images.githubusercontent.com/48059714/66841747-729d6400-ef6a-11e9-9845-f99401d6802c.jpg)
![photo_2019-10-15_16-39-42](https://user-images.githubusercontent.com/48059714/66841748-7335fa80-ef6a-11e9-99f5-d7e3038ff419.jpg)

**Comment by DaniDru** [comment]
Knobs para los potenciómetros de un generador de ondas cuadradas DIY basado en el Atari Punk Console. 
![photo_2019-11-13_23-28-18](https://user-images.githubusercontent.com/48059714/68810233-f469d580-066d-11ea-8196-5b45c145800e.jpg)
![photo_2019-11-13_23-28-26](https://user-images.githubusercontent.com/48059714/68810234-f469d580-066d-11ea-8f38-632e06bf2633.jpg)
![photo_2019-11-13_23-28-30](https://user-images.githubusercontent.com/48059714/68810235-f5026c00-066d-11ea-9e02-484ecec06083.jpg)
![photo_2019-11-13_23-28-33](https://user-images.githubusercontent.com/48059714/68810236-f5026c00-066d-11ea-8f4a-53bb146ee553.jpg)

**Comment by JorFru** [comment]
Esa anet imprime como dios

pásame ese STL (mejor link a thingiverse) que quiero imprimir unos yo también.

**Comment by MrTommyGuns** [comment]
@DaniDru ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.

Enhorabuena ☺️
