### ISSUE TITLE
Quiero ser operador

### ISSUE THREAD

**Issue by Petikuis** [asrob-uc3m/operadores#53]
Quiero usar las impresoras y estoy en grupo de impresoras de asrob

**Comment by Petikuis** [comment]
![IMG_20191010_195257](https://user-images.githubusercontent.com/56403243/66594084-a5c1ab00-eb98-11e9-9390-6197f825c288.jpg)

Ya he hecho mi primera pieza pero se ha imprimido mal. Puede ser por haberlo calibrado rápido

**Comment by JorFru** [comment]
Esa moneda/llaverlo te va a quedar mejor impresa en vertical
No kidding

**Comment by Petikuis** [comment]
Ya he terminado la segunda pieza.
![IMG_20191017_185708](https://user-images.githubusercontent.com/56403243/67030732-589d8600-f110-11e9-9684-351413ab4e97.jpg)

**Comment by Petikuis** [comment]
![IMG_20191024_231142](https://user-images.githubusercontent.com/56403243/67689641-e6dcfc00-f99b-11e9-8498-f2c8eca78ca8.jpg)
Ya he impreso la tercera pieza.

**Comment by MrTommyGuns** [comment]
@Petikuis ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.

Enhorabuena ☺️
