### ISSUE TITLE
Quiero ser operadora

### ISSUE THREAD

**Issue by luciagz02** [asrob-uc3m/operadores#56]
![20191020_203400](https://user-images.githubusercontent.com/56801101/67514476-14286200-f69d-11e9-8d41-d6c5060036e1.jpg)

**Comment by luciagz02** [comment]
![20191024_224612](https://user-images.githubusercontent.com/56801101/67561357-f6024680-f71c-11e9-8f7e-77b1000275ce.jpg)

**Comment by luciagz02** [comment]
![IMG_20191114_203614_155](https://user-images.githubusercontent.com/56801101/68892090-774c6800-0722-11ea-9774-86e0a60beedb.jpg)

**Comment by MrTommyGuns** [comment]
@luciagz02  ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operadora.

Enhorabuena ☺️
