### ISSUE TITLE
Quiero ser operador

### ISSUE THREAD

**Issue by Serrano492** [asrob-uc3m/operadores#60]
Quiero ser operador porque estoy en el grupo de Printer one y quiero imprimir y cacharrear

**Comment by Serrano492** [comment]
Bill cipher de PLA tamaño llavero

**Comment by Serrano492** [comment]
![Uploading IMG_20191205_180532.jpg…]()
Cubo de calibración en Hija Resurrección

**Comment by Serrano492** [comment]
![15816238349741862903865965765454](https://user-images.githubusercontent.com/58563743/74473390-ce89e200-4ea3-11ea-8b1a-d235d7999a1b.jpg)
Bill Cypher agrandado

**Comment by MrTommyGuns** [comment]
@Serrano492  ha demostrado que tiene los conocimientos actualmente recogidos en el manual de usuario y ha realizado las impresiones supervisadas necesarias siendo suficiente para convertirse en operador.

Enhorabuena ☺️
