### ISSUE TITLE
Quiero ser operador

### ISSUE THREAD

**Issue by cterresmo** [asrob-uc3m/operadores#62]
Hola,
Soy Carlos y estudio electrónica industrial y automática en leganés-
Quiero hacerme operador de impresoras 3d para algunos proyectos.
Gracias!

**Comment by fervh** [comment]
Me encargo de tu formación Carlos
El viernes a partir de la 1 pm??

**Comment by cterresmo** [comment]
ok

**Comment by cterresmo** [comment]
Subo unas cotillos de proceso. Gracias Fer!
![E952577C-F248-4852-97CE-AD51E2CF734B](https://user-images.githubusercontent.com/58704369/70912937-4ad38680-2015-11ea-8d33-da105faf358d.jpeg)
![2F6F880A-78A2-47C4-87C4-0E85B4D3D0E7](https://user-images.githubusercontent.com/58704369/70912938-4c04b380-2015-11ea-929a-ed77a2018681.jpeg)
![2D82F432-9003-4F3E-8942-D7808BB69EB7](https://user-images.githubusercontent.com/58704369/70912939-4c04b380-2015-11ea-9d36-2183257e2c8f.jpeg)
![F567B0D1-A696-4DC9-B353-5A8D1A85D823](https://user-images.githubusercontent.com/58704369/70912941-4c9d4a00-2015-11ea-876f-093f5a379bcf.jpeg)

**Comment by cterresmo** [comment]
![WhatsApp Image 2019-12-19 at 11 01 43](https://user-images.githubusercontent.com/58704369/74167061-f1a85d80-4c27-11ea-8d1f-c92402fe58b7.jpeg)

**Comment by cterresmo** [comment]
que guay fernando!
