### ISSUE TITLE
Ser operador

### ISSUE THREAD

**Issue by daavm** [asrob-uc3m/operadores#9]
Hola!

Hemos hablado hoy con @Siotma y me gustaría ser operador. Aquí van las cosillas que he ido imprimiendo mientras trabajábamos con Dédalo las últimas semanas, con su ayuda y formación.

![32176796-ec9e16ca-bd88-11e7-9367-7258d2eff5dc](https://user-images.githubusercontent.com/14359236/33349229-8e5fcf2c-d499-11e7-8e96-ce92cc4a284f.jpg)

![33230511-23afa10e-d1e5-11e7-952c-cdd6861ef5f9](https://user-images.githubusercontent.com/14359236/33349234-9154000e-d499-11e7-8697-81434b22bd0b.jpg)

![photo5832606725621000908](https://user-images.githubusercontent.com/14359236/33349237-9493475c-d499-11e7-97d4-5c75abd7fa4b.jpg)

**Comment by Siotma** [comment]
@daavm ha demostrado en las sucesivas reuniones de Printer One que tiene los conocimientos actualmente recogidos en el [manual de usuario](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/), así como experiencia siendo ambos más que suficientes como para convertirse en operador.
